import 'dart:developer' show log;
import 'dart:io' show File, Directory, HttpHeaders, Platform;

import 'package:audio_service/audio_service.dart';
import 'package:connectivity_plus/connectivity_plus.dart';
// import 'package:dio/dio.dart' as d;
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter_cache_manager/flutter_cache_manager.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_sliding_panel/flutter_sliding_panel.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:get/get.dart' hide Response;
import 'package:get_storage/get_storage.dart';
import 'package:just_audio/just_audio.dart';
import 'package:lottie/lottie.dart';
import 'package:path/path.dart';
import 'package:path_provider/path_provider.dart';
import 'package:rxdart/rxdart.dart' as r;

import '/core/extensions/string_extensions.dart';
import '/core/utils/ui_helper.dart';
import '/core/widgets/custom_paint/custom_slider.dart';
import '/quran.dart';
import '../core/constants/lottie_constants.dart';

part '../audio/constants/readers_constants.dart';
part '../audio/constants/storage_constants.dart';
part '../audio/core/utils/custom_widgets.dart';
part '../audio/data/model/ayah_audio_style.dart';
part '../audio/data/model/surah_audio_style.dart';
part '../audio/surah_audio/controller/audio_player_handler.dart';
part '../audio/surah_audio/controller/extensions/ayah_ctrl_extension.dart';
part '../audio/surah_audio/controller/extensions/surah_audio_getters.dart';
part '../audio/surah_audio/controller/extensions/surah_audio_storage_getters.dart';
part '../audio/surah_audio/controller/extensions/surah_audio_ui.dart';
part '../audio/surah_audio/controller/extensions/surah_ctrl_extension.dart';
part '../audio/surah_audio/controller/surah_audio_state.dart';
part '../audio/surah_audio/widgets/back_drop_widget.dart';
part '../audio/surah_audio/widgets/change_reader.dart';
part '../audio/surah_audio/widgets/collapsed_play_widget.dart';
part '../audio/surah_audio/widgets/download_play_button.dart';
part '../audio/surah_audio/widgets/last_listen.dart';
part '../audio/surah_audio/widgets/play_banner.dart';
part '../audio/surah_audio/widgets/play_widget.dart';
part '../audio/surah_audio/widgets/repeat_widget.dart';
part '../audio/surah_audio/widgets/surah_audio_list.dart';
part '../audio/surah_audio/widgets/surah_seek_bar.dart';
part '../audio/surah_audio/widgets/surah_skip_next.dart';
part '../audio/surah_audio/widgets/surah_skip_previouse.dart';
part '../audio/widgets/audio_widget.dart';
part '../audio/widgets/change_reader.dart';
part '../audio/widgets/online_play_button.dart';
part '../audio/widgets/play_ayah_widget.dart';
part '../audio/widgets/seek_bar.dart';
part 'surah_audio/controller/audio_ctrl.dart';
part 'surah_audio/surah_audio_screen.dart';
part 'widgets/ayah_skip_next.dart';
part 'widgets/ayah_skip_previouse.dart';
