import 'dart:async';
import 'dart:developer' show log;
import 'dart:io' show File, Directory, HttpHeaders, Platform;

import 'package:audio_service/audio_service.dart';
import 'package:connectivity_plus/connectivity_plus.dart';
// import 'package:dio/dio.dart' as d;
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter_cache_manager/flutter_cache_manager.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_sliding_panel/flutter_sliding_panel.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:get/get.dart' hide Response;
import 'package:get_storage/get_storage.dart';
import 'package:just_audio/just_audio.dart';
import 'package:lottie/lottie.dart';
import 'package:path/path.dart';
import 'package:path_provider/path_provider.dart';
import 'package:rxdart/rxdart.dart' as r;

import '../quran/core/utils/ui_helper.dart';
import '/quran.dart';
import 'constants/lottie_constants.dart';
import 'core/custom_paint/custom_slider.dart';
import 'core/extensions/string_extensions.dart';

part 'constants/readers_constants.dart';
part 'constants/storage_constants.dart';
part 'core/utils/custom_widgets.dart';
part 'data/model/ayah_audio_style.dart';
part 'data/model/surah_audio_style.dart';
part 'surah_audio/controller/audio_ctrl.dart';
part 'surah_audio/controller/audio_handler.dart';
part 'surah_audio/controller/extensions/ayah_ctrl_extension.dart';
part 'surah_audio/controller/extensions/surah_audio_storage.dart';
part 'surah_audio/controller/extensions/surah_ctrl_extension.dart';
part 'surah_audio/controller/extensions/surah_getters.dart';
part 'surah_audio/controller/extensions/surah_ui.dart';
part 'surah_audio/controller/surah_state.dart';
part 'surah_audio/surah_audio_screen.dart';
part 'surah_audio/widgets/surah_audio_list.dart';
part 'surah_audio/widgets/surah_back_drop_widget.dart';
part 'surah_audio/widgets/surah_change_reader.dart';
part 'surah_audio/widgets/surah_collapsed_play_widget.dart';
part 'surah_audio/widgets/surah_download_play_button.dart';
part 'surah_audio/widgets/surah_last_listen.dart';
part 'surah_audio/widgets/surah_online_play_button.dart';
part 'surah_audio/widgets/surah_play_banner.dart';
part 'surah_audio/widgets/surah_play_widget.dart';
part 'surah_audio/widgets/surah_repeat_widget.dart';
part 'surah_audio/widgets/surah_seek_bar.dart';
part 'surah_audio/widgets/surah_skip_next.dart';
part 'surah_audio/widgets/surah_skip_previouse.dart';
part 'widgets/ayah_audio_widget.dart';
part 'widgets/ayah_change_reader.dart';
part 'widgets/ayah_skip_next.dart';
part 'widgets/ayah_skip_previouse.dart';
part 'widgets/package_seek_bar.dart';
part 'widgets/play_ayah_widget.dart';
